# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao_Bancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bancada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Bancada')),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Politico')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador', models.CharField(max_length=200)),
                ('valor', models.IntegerField(default=0)),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Politico')),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='id_eleitoral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='total_doacao',
            field=models.IntegerField(default=0),
        ),
    ]
