# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleito', models.BooleanField(default=True)),
                ('inicio_periodo', models.DateTimeField(verbose_name='Inicio da Candidatura')),
                ('final_periodo', models.DateTimeField(verbose_name='Final da Candidatura')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('salario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobre_nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('cargo_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politico.Cargo')),
                ('partido_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politico.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio_andamento_projeto', models.DateTimeField(verbose_name='Inicio do andamento do projeto')),
                ('andamento', models.CharField(max_length=200)),
                ('data_andamento', models.DateTimeField(verbose_name='Data do andamento atual')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politico.Politico')),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='politico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politico.Politico'),
        ),
    ]
