# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politico',
            name='cargo_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='politico.Cargo'),
        ),
        migrations.AlterField(
            model_name='politico',
            name='partido_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='politico.Partido'),
        ),
    ]
